import { culms } from '../app.js';
import { currentUser } from '../guard.js';
import { html } from '../ui/render.js';
import { formatDate, availabilityLabel } from '../ui/format.js';
import { showResultError, showToast } from '../ui/toast.js';
const isbn = new URLSearchParams(location.search).get('isbn'); const detail = isbn ? culms.catalogue.getBookDetail(isbn) : { ok: false };
const main = document.querySelector('main');
function badge(status) { return status === 'Available' ? 'bg-success' : status === 'Reserved' ? 'bg-warning text-dark' : 'bg-secondary'; }
function renderReserve(book) { const panel = document.querySelector('#reserve-panel'); const user = currentUser(); const available = book.copies.some(copy => copy.status === 'Available'); if (!user) { panel.innerHTML = '<div class="alert alert-info">Log in as a Student or Professor to reserve. <a class="btn btn-primary btn-sm ms-2" href="login.html?next=book.html%3Fisbn%3D' + encodeURIComponent(book.isbn) + '">Login</a></div>'; return; } if (!['Student', 'Professor'].includes(user.role)) { panel.innerHTML = '<div class="alert alert-info">Only students and professors can reserve books.</div>'; return; } const active = culms.reservations.getActiveReservation(user.id, book.isbn); if (active) { panel.innerHTML = html`<div class="alert alert-success">Reservation ${active.confirmationCode} is ${active.status}. Expires ${formatDate(active.expirationDate)}.</div>`; return; } if (available) { panel.innerHTML = '<div class="alert alert-info">Copies are available on the shelf. Please pick up the book in person.</div>'; return; } panel.innerHTML = '<button id="reserve-button" class="btn btn-primary">Reserve this book</button>'; document.querySelector('#reserve-button').addEventListener('click', () => { const result = culms.reservations.reserveBook(user.id, book.isbn); if (!result.ok) { showResultError(result); return; } showToast('Book reserved successfully.', 'success'); document.dispatchEvent(new CustomEvent('culms:changed')); renderReserve(book); }); }
function render(book) { document.querySelector('#book-title').textContent = book.title; document.querySelector('#book-author').textContent = book.author; document.querySelector('#book-isbn').textContent = book.isbn; document.querySelector('#book-category').textContent = book.category; const campuses = [...new Set(book.copies.map(copy => copy.campus))].sort(); document.querySelector('#campus-rows').innerHTML = campuses.map(campus => { const copies = book.copies.filter(copy => copy.campus === campus); return html`<tr><td>${campus}</td><td>${copies.length}</td><td>${copies.filter(copy => copy.status === 'Available').length}</td><td>${copies.filter(copy => copy.status === 'OnLoan').length}</td><td>${copies.filter(copy => copy.status === 'CourseReserve' || copy.courseReserve).length}</td></tr>`; }).join(''); document.querySelector('#copy-rows').innerHTML = book.copies.map(copy => html`<tr><td>${copy.barcode}</td><td>${copy.campus}</td><td>${copy.shelfLocation}</td><td>${copy.conditionStatus}</td><td><span class="badge ${badge(copy.status)}">${availabilityLabel(copy.status)}</span></td></tr>`).join(''); renderReserve(book); }
if (!detail.ok) { main.innerHTML = '<section class="container py-5"><div class="alert alert-warning">We could not find that book. <a href="books.html">Return to the catalogue</a>.</div></section>'; } else { render(detail.data); }
