import { culms } from '../app.js';
import { html } from '../ui/render.js';
import { availabilityLabel, buildBookQuery, campusAvailability, parseBookQuery } from '../ui/format.js';
const state = parseBookQuery(location.search); const pageSize = 9;
const badgeClass = status => status === 'Available' ? 'bg-success' : status === 'Reserved' ? 'bg-warning text-dark' : 'bg-secondary';
function options(values, selected) { return values.map(value => html`<option value=\"${value}\"${value === selected ? ' selected' : ''}>${value}</option>`).join(''); }
function renderFilters() { document.querySelector('#campus').innerHTML = `<option value="">All campuses</option>${options(culms.catalogue.listCampuses(), state.campus)}`; document.querySelector('#category').innerHTML = `<option value="">All categories</option>${options(culms.catalogue.listCategories(), state.category)}`; document.querySelector('#query').value = state.query; document.querySelector('#availableOnly').checked = state.availableOnly; document.querySelector('#sortBy').value = state.sortBy; }
function renderResults(rows) { const totalPages = Math.max(1, Math.ceil(rows.length / pageSize)); state.page = Math.min(state.page, totalPages); const visible = rows.slice((state.page - 1) * pageSize, state.page * pageSize); document.querySelector('#result-count').textContent = `${rows.length} result${rows.length === 1 ? '' : 's'}`; document.querySelector('#results').innerHTML = visible.length ? visible.map(row => { const availability = campusAvailability(row.campusStats); return html`<div class="col-md-6 col-lg-4"><div class="bg-light rounded p-4 h-100"><h4 class="mb-2"><a href="book.html?isbn=${row.isbn}">${row.title}</a></h4><p class="mb-2">${row.author}</p><span class="badge bg-primary me-1">${row.category}</span><span class="badge ${badgeClass(row.status)}">${availabilityLabel(row.status)}</span><p class="mt-3 mb-0">${availability.available} copies available at ${availability.campuses} of ${availability.total} campuses</p></div></div>`; }).join('') : '<div class="col-12"><div class="alert alert-info">No books matched your search. Try a different title, author, ISBN or filter.</div></div>'; document.querySelector('#pagination').innerHTML = totalPages > 1 ? Array.from({ length: totalPages }, (_, index) => `<li class="page-item${index + 1 === state.page ? ' active' : ''}"><a class="page-link" href="${buildBookQuery({ ...state, page: index + 1 })}">${index + 1}</a></li>`).join('') : ''; }
function search() { const values = { query: document.querySelector('#query').value.trim(), campus: document.querySelector('#campus').value, category: document.querySelector('#category').value, availableOnly: document.querySelector('#availableOnly').checked, sortBy: document.querySelector('#sortBy').value, page: 1 }; location.href = `books.html${buildBookQuery(values)}`; }
renderFilters(); document.querySelector('#search-form').addEventListener('submit', event => { event.preventDefault(); search(); });
const result = culms.catalogue.searchBooks(state); renderResults(result.ok ? result.data : []);
