const library = children => ({ label: 'My Library', children, enabled: true });
export const navConfig = {
  Guest: [{ label: 'Home', href: 'index.html', enabled: true }, { label: 'Services', href: 'service.html', enabled: true }, { label: 'About', href: 'about.html', enabled: true }, { label: 'Help Desk', href: 'contact.html', enabled: true }, { label: 'Login', href: 'login.html', enabled: true }],
  Student: [{ label: 'Books', href: 'books.html', enabled: true }, library([{ label: 'My Dashboard', href: 'student.html', enabled: true }, { label: 'My Loans', href: 'my-loans.html', enabled: true }, { label: 'My Reservations', href: 'my-reservations.html', enabled: true }, { label: 'My Fines', href: 'my-fines.html', enabled: true }, { label: 'My History', href: 'my-history.html', enabled: true }])],
  Professor: [{ label: 'Books', href: 'books.html', enabled: true }, library([{ label: 'My Dashboard', href: 'professor.html', enabled: true }, { label: 'My Loans', href: 'my-loans.html', enabled: true }, { label: 'My Reservations', href: 'my-reservations.html', enabled: true }, { label: 'My Fines', href: 'my-fines.html', enabled: true }, { label: 'My History', href: 'my-history.html', enabled: true }, { label: 'Course Reserve', href: 'course-reserve.html', enabled: true }, { label: 'Acquisitions', href: 'acquisitions.html', enabled: true }])],
  Librarian: [{ label: 'Dashboard', href: 'librarian.html', enabled: true }, { label: 'Books', href: 'books.html', enabled: true }, { label: 'Desk', enabled: true, children: [{ label: 'Checkout', href: 'checkout.html', enabled: true, permission: 'PROCESS_LOANS' }, { label: 'Return', href: 'return.html', enabled: true, permission: 'PROCESS_LOANS' }, { label: 'Overdue', href: 'overdue.html', enabled: true, permission: 'PROCESS_LOANS' }, { label: 'Fines Desk', href: 'fines-desk.html', enabled: true, permission: 'MANAGE_FINES' }] }, { label: 'Catalogue', href: 'manage-catalogue.html', enabled: true, permission: 'MANAGE_CATALOGUE' }],
  Administrator: [{ label: 'Dashboard', href: 'admin.html', enabled: true }, { label: 'Books', href: 'books.html', enabled: true }]
};
export function visibleNav(role, permissions = []) { return (navConfig[role] || navConfig.Guest).filter(item => item.enabled && (!item.permission || permissions.includes(item.permission))).map(item => item.children ? { ...item, children: item.children.filter(child => child.enabled && (!child.permission || permissions.includes(child.permission))) } : item).filter(item => !item.children || item.children.length); }
