/// <reference lib="webworker" />

/* eslint-disable no-restricted-globals */
import { CacheableResponsePlugin } from 'workbox-cacheable-response';
import { clientsClaim, skipWaiting } from 'workbox-core';
import { ExpirationPlugin } from 'workbox-expiration';
import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst, NetworkFirst, StaleWhileRevalidate } from 'workbox-strategies';

declare const self: ServiceWorkerGlobalScope;

// Activate updated service worker right away.
skipWaiting();
clientsClaim();

// Precache files generated by the build (JS, CSS, index.html, etc).
precacheAndRoute(self.__WB_MANIFEST);

// 1) CacheFirst: static assets load fast, even when offline.
registerRoute(
  ({ request, url }) =>
    request.method === 'GET' &&
    url.origin === self.location.origin &&
    (request.destination === 'style' ||
      request.destination === 'script' ||
      request.destination === 'image' ||
      request.destination === 'font'),
  new CacheFirst({
    cacheName: 'elitrack-static-v2',
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new ExpirationPlugin({
        maxEntries: 120,
        maxAgeSeconds: 30 * 24 * 60 * 60,
      }),
    ],
  })
);

// 2) NetworkFirst: API tries network first, then falls back to cached data.
registerRoute(
  ({ request, url }) =>
    request.method === 'GET' &&
    (url.pathname.startsWith('/api/') || url.pathname.includes('/api/')),
  new NetworkFirst({
    cacheName: 'elitrack-api-v2',
    networkTimeoutSeconds: 5,
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new ExpirationPlugin({
        maxEntries: 80,
        maxAgeSeconds: 24 * 60 * 60,
      }),
    ],
  })
);

// 3) Runtime caching for page navigations: keeps the app shell available offline.
registerRoute(
  ({ request }) => request.mode === 'navigate',
  new NetworkFirst({
    cacheName: 'elitrack-pages-v2',
    networkTimeoutSeconds: 3,
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new ExpirationPlugin({
        maxEntries: 20,
        maxAgeSeconds: 7 * 24 * 60 * 60,
      }),
    ],
  })
);

// 4) Runtime caching for external Google Fonts.
registerRoute(
  ({ url }) =>
    url.origin === 'https://fonts.googleapis.com' || url.origin === 'https://fonts.gstatic.com',
  new StaleWhileRevalidate({
    cacheName: 'elitrack-fonts-v1',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 30,
        maxAgeSeconds: 60 * 24 * 60 * 60,
      }),
    ],
  })
);
