# Generated by Django 6.0.6 on 2026-07-03 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], db_index=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacts', to=settings.AUTH_USER_MODEL)),
                ('witnesses', models.ManyToManyField(blank=True, related_name='witnessed_pacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('note', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='checkins/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], db_index=True, default='pending', max_length=10)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins_submitted', to=settings.AUTH_USER_MODEL)),
                ('pact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='habits.pact')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject')], db_index=True, max_length=10)),
                ('responded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('comment', models.TextField(blank=True)),
                ('check_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='habits.checkin')),
                ('witness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications_given', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted')], db_index=True, default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('addressee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friend_requests', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='habits_frie_status_f55da3_idx'), models.Index(fields=['created_at'], name='habits_frie_created_f2ef00_idx')],
                'constraints': [models.UniqueConstraint(fields=('requester', 'addressee'), name='unique_friend_request_pair'), models.CheckConstraint(condition=models.Q(('requester', models.F('addressee')), _negated=True), name='friendship_distinct_users')],
            },
        ),
        migrations.AddIndex(
            model_name='pact',
            index=models.Index(fields=['owner', 'is_active'], name='habits_pact_owner_i_1e4a0e_idx'),
        ),
        migrations.AddIndex(
            model_name='pact',
            index=models.Index(fields=['frequency'], name='habits_pact_frequen_82075f_idx'),
        ),
        migrations.AddIndex(
            model_name='pact',
            index=models.Index(fields=['created_at'], name='habits_pact_created_806c72_idx'),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['status'], name='habits_chec_status_bb248d_idx'),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['timestamp'], name='habits_chec_timesta_4be61b_idx'),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['pact', 'status'], name='habits_chec_pact_id_29ebf3_idx'),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['submitted_by', 'timestamp'], name='habits_chec_submitt_07d9a8_idx'),
        ),
        migrations.AddIndex(
            model_name='verification',
            index=models.Index(fields=['decision'], name='habits_veri_decisio_aeff7c_idx'),
        ),
        migrations.AddIndex(
            model_name='verification',
            index=models.Index(fields=['responded_at'], name='habits_veri_respond_8c1cf1_idx'),
        ),
        migrations.AddIndex(
            model_name='verification',
            index=models.Index(fields=['check_in', 'decision'], name='habits_veri_check_i_cf6264_idx'),
        ),
        migrations.AddConstraint(
            model_name='verification',
            constraint=models.UniqueConstraint(fields=('check_in', 'witness'), name='unique_verification_per_witness'),
        ),
    ]
